CREATE TABLE IF NOT EXISTS task_status (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
